kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/ch1aki/check-ftp

steps:
- name: test
  image: golang
  environment:
    GO111MODULE: on
  commands:
  - go get
  - go test

- name: build
  image: golang
  environment:
    GO111MODULE: on
  commands:
  - go get github.com/Songmu/goxz/cmd/goxz
  - goxz -d dist/${DRONE_TAG} -z -os windows,darwin,linux -arch amd64,386

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: dist/${DRONE_TAG}/*
  when:
    event: tag
  ref:
    include:
      - refs/tags/v*.*.*